spring.application.name=military-asset-management
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5432/kristallball_project
spring.datasource.username=postgres
spring.datasource.password=12341234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=change-this-secret-to-a-long-random-secret-key-at-least-32-bytes
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
